// Configuration constants
const CONFIG = {
    // Map defaults
    mapCenter: [-98.5795, 39.8283], // Center of USA (lon, lat)
    mapZoom: 5,
    maxZoom: 18,
    minZoom: 3,
    
    // Game balance
    initialCitizens: 3,
    initialFood: 100,
    initialSeeds: 20,
    initialScrap: 50,
    initialHappiness: 70,
    
    // Building costs
    buildCost: 100, // legacy, not used
    buildTime: 5000, // milliseconds
    
    // Leveling
    xpPerBase: 50,
    xpPerLevel: 100,
    
    // OSM defaults
    osmTileUrl: 'http://{a-c}.tile.openstreetmap.org/{z}/{x}/{y}.png',
    
    // Storage keys
    storagePrefix: 'claimconstruct_',
    
    // Building types definition
    BUILDINGS: {
        HQ: {
            id: 'hq',
            name: 'Headquarters',
            description: 'Central base and town center',
            defense: 500,
            bedsMin: 10,
            bedsMax: 20,
            storageCapacity: 500,
            jobSlots: 2,
            osmTypes: ['house', 'residential'],
            buildCost: 0,
            buildTime: 0,
            unique: true, // Only one allowed
        },
        HOUSE: {
            id: 'house',
            name: 'House',
            description: 'Residential building',
            defense: 100,
            bedsMin: 6,
            bedsMax: 12,
            storageCapacity: 50,
            osmTypes: ['house', 'residential'], // Can be claimed from OSM
            buildCost: 150,
            buildTime: 3000,
        },
        COTTAGE_BLOCK: {
            id: 'cottage_block',
            name: 'Cottage Block',
            description: 'Cluster of detached and terrace homes',
            defense: 110,
            bedsMin: 8,
            bedsMax: 14,
            storageCapacity: 60,
            jobSlots: 1,
            osmTypes: ['detached', 'terrace'],
            strictOsmMatch: true,
            buildCost: 190,
            buildTime: 3800,
        },
        ROW_HOUSING: {
            id: 'row_housing',
            name: 'Row Housing',
            description: 'Dense rowhouse district converted for civilian housing',
            defense: 112,
            bedsMin: 9,
            bedsMax: 15,
            storageCapacity: 65,
            jobSlots: 1,
            osmTypes: ['terrace', 'row_house'],
            strictOsmMatch: true,
            buildCost: 200,
            buildTime: 3900,
        },
        TENEMENT: {
            id: 'tenement',
            name: 'Tenement Block',
            description: 'Upgraded multi-family residence with compact utilities',
            defense: 118,
            bedsMin: 12,
            bedsMax: 20,
            storageCapacity: 75,
            jobSlots: 2,
            osmTypes: ['residential', 'apartments'],
            buildCost: 240,
            buildTime: 4700,
        },
        APARTMENT_BUILDING: {
            id: 'apartment_building',
            name: 'Apartment Building',
            description: 'High-capacity residential complex',
            defense: 130,
            bedsMin: 20,
            bedsMax: 30,
            storageCapacity: 120,
            osmTypes: ['apartments'],
            strictOsmMatch: true,
            buildCost: 320,
            buildTime: 6500,
        },
        HIGH_RISE_TOWER: {
            id: 'high_rise_tower',
            name: 'High-Rise Tower',
            description: 'Vertical housing tower with large civilian capacity',
            defense: 140,
            bedsMin: 24,
            bedsMax: 36,
            storageCapacity: 140,
            jobSlots: 2,
            osmTypes: ['tower'],
            strictOsmMatch: true,
            buildCost: 360,
            buildTime: 7000,
        },
        HOSTEL: {
            id: 'hostel',
            name: 'Hostel Complex',
            description: 'Dormitory and hotel facilities repurposed for housing',
            defense: 120,
            bedsMin: 14,
            bedsMax: 24,
            storageCapacity: 80,
            jobSlots: 2,
            osmTypes: ['dormitory', 'hotel'],
            strictOsmMatch: true,
            buildCost: 280,
            buildTime: 5200,
        },
        RESIDENTIAL_COMPLEX: {
            id: 'residential_complex',
            name: 'Residential Complex',
            description: 'Planned residential district with shared services',
            defense: 125,
            bedsMin: 16,
            bedsMax: 26,
            storageCapacity: 95,
            jobSlots: 2,
            osmTypes: ['residential', 'apartments', 'dormitory'],
            buildCost: 300,
            buildTime: 5600,
        },
        FARM: {
            id: 'farm',
            name: 'Farm',
            description: 'Produces food from seeds',
            defense: 150,
            jobSlots: 5,
            osmTypes: ['farm', 'farmland'],
            strictOsmMatch: true,
            buildCost: 0,
            buildTime: 0,
            unique: false,
        },
        FIELD_KITCHEN: {
            id: 'field_kitchen',
            name: 'Field Kitchen',
            description: 'Distributed food preparation site near settlements',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['yes'],
            buildCost: 290,
            buildTime: 5400,
        },
        GATHERING_STATION: {
            id: 'gathering_station',
            name: 'Gathering Station',
            description: 'Collects food and seeds',
            defense: 150,
            jobSlots: 4,
            osmTypes: ['forest', 'wood'],
            strictOsmMatch: true,
            buildCost: 250,
            buildTime: 5000,
        },
        STORAGE: {
            id: 'storage',
            name: 'Storage Facility',
            description: 'Stores resources',
            defense: 150,
            storageCapacity: 200,
            osmTypes: ['warehouse', 'storage'],
            strictOsmMatch: true,
            buildCost: 300,
            buildTime: 8000,
        },
        STOREHOUSE: {
            id: 'storehouse',
            name: 'Storehouse',
            description: 'Basic resource storage built from repurposed structures',
            defense: 150,
            storageCapacity: 100,
            osmTypes: ['yes'],
            buildCost: 220,
            buildTime: 4500,
        },
        ARMORY: {
            id: 'armory',
            name: 'Armory',
            description: 'Military training facility',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['barracks', 'bunker'],
            buildCost: 400,
            scrapCost: 100,
            buildTime: 10000,
        },
        GUNSMITH: {
            id: 'gunsmith',
            name: 'Gunsmith',
            description: 'Crafts and maintains weapons to improve soldier effectiveness',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['workshop'],
            strictOsmMatch: true,
            buildCost: 360,
            scrapCost: 80,
            toolCost: 4,
            buildTime: 9000,
        },
        TRAINING_GROUNDS: {
            id: 'training_grounds',
            name: 'Training Grounds',
            description: 'Dedicated drill and tactics area for soldier development',
            defense: 180,
            jobSlots: 3,
            osmTypes: ['barracks', 'military', 'yes'],
            buildCost: 430,
            scrapCost: 110,
            buildTime: 9800,
        },
        MUNITIONS_FACTORY: {
            id: 'munitions_factory',
            name: 'Munitions Factory',
            description: 'Produces military ordnance and supports advanced units',
            defense: 220,
            jobSlots: 2,
            osmTypes: ['industrial', 'factory'],
            strictOsmMatch: true,
            buildCost: 460,
            scrapCost: 130,
            toolCost: 6,
            buildTime: 10400,
        },
        WAR_COLLEGE: {
            id: 'war_college',
            name: 'War College',
            description: 'Elite strategic command center for military doctrine',
            defense: 260,
            jobSlots: 2,
            osmTypes: ['military'],
            strictOsmMatch: true,
            buildCost: 520,
            scrapCost: 160,
            toolCost: 8,
            buildTime: 11200,
        },
        RELIGIOUS: {
            id: 'religious',
            name: 'Religious Site',
            description: 'Provides spiritual guidance and stability',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['place_of_worship', 'church', 'mosque', 'temple', 'synagogue'],
            strictOsmMatch: true,
            buildCost: 300,
            buildTime: 7000,
        },
        FORTIFICATION: {
            id: 'fortification',
            name: 'Fortification',
            description: 'Heavily defended military structure',
            defense: 1000,
            osmTypes: ['fort', 'fortress'],
            buildCost: 500,
            scrapCost: 150,
            buildTime: 12000,
        },
        CASTLE_KEEP: {
            id: 'castle_keep',
            name: 'Castle Keep',
            description: 'Converted castle or bunker used for garrison command',
            defense: 850,
            jobSlots: 2,
            osmTypes: ['castle'],
            strictOsmMatch: true,
            buildCost: 520,
            scrapCost: 160,
            buildTime: 11800,
        },
        PALISADE: {
            id: 'palisade',
            name: 'Palisade',
            description: 'Reinforced perimeter wall for early defensive coverage',
            defense: 700,
            jobSlots: 1,
            osmTypes: ['wall', 'fence', 'defensive'],
            buildCost: 460,
            scrapCost: 120,
            buildTime: 10200,
        },
        BASTION: {
            id: 'bastion',
            name: 'Bastion',
            description: 'Layered defensive strongpoint with hardened positions',
            defense: 1200,
            jobSlots: 2,
            osmTypes: ['fort', 'fortress', 'bunker'],
            strictOsmMatch: true,
            buildCost: 560,
            scrapCost: 180,
            toolCost: 7,
            buildTime: 12400,
        },
        CITADEL: {
            id: 'citadel',
            name: 'Citadel',
            description: 'Peak-tier fortress command node with maximal defense',
            defense: 1500,
            jobSlots: 2,
            osmTypes: ['citadel'],
            strictOsmMatch: true,
            buildCost: 640,
            scrapCost: 220,
            toolCost: 10,
            buildTime: 13200,
        },
        ENTERTAINMENT: {
            id: 'entertainment',
            name: 'Entertainment Venue',
            description: 'Theater, tavern, or gathering place for morale',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['theatre', 'cinema'],
            strictOsmMatch: true,
            buildCost: 250,
            buildTime: 5000,
        },
        NIGHTCLUB: {
            id: 'nightclub',
            name: 'Nightclub Hall',
            description: 'Music-focused venue that boosts morale quickly',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['nightclub'],
            strictOsmMatch: true,
            buildCost: 265,
            buildTime: 5200,
        },
        BREWERY: {
            id: 'brewery',
            name: 'Brewery',
            description: 'Produces beverages from seeds for happiness',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['brewery'],
            strictOsmMatch: true,
            buildCost: 300,
            buildTime: 6000,
        },
        WORKSHOP: {
            id: 'workshop',
            name: 'Workshop',
            description: 'Builds tools and refines salvaged materials',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['workshop', 'industrial'],
            strictOsmMatch: true,
            buildCost: 320,
            scrapCost: 40,
            buildTime: 6500,
        },
        CLINIC: {
            id: 'clinic',
            name: 'Clinic',
            description: 'Improves morale through healthcare and support',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['clinic', 'hospital'],
            strictOsmMatch: true,
            buildCost: 350,
            buildTime: 7000,
        },
        WATERWORKS: {
            id: 'waterworks',
            name: 'Waterworks',
            description: 'Improves irrigation and agricultural output',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['water_tower', 'water_works'],
            strictOsmMatch: true,
            buildCost: 340,
            scrapCost: 40,
            buildTime: 7000,
        },
        PUMPING_STATION: {
            id: 'pumping_station',
            name: 'Pumping Station',
            description: 'Water distribution site that supports crop reliability',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['pumping_station'],
            strictOsmMatch: true,
            buildCost: 335,
            buildTime: 6900,
        },
        ORCHARD: {
            id: 'orchard',
            name: 'Orchard Estate',
            description: 'Seasonal fruit plots that produce food and some seeds',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['orchard', 'vineyard'],
            strictOsmMatch: true,
            buildCost: 330,
            buildTime: 6500,
        },
        GREENHOUSE: {
            id: 'greenhouse',
            name: 'Greenhouse',
            description: 'Controlled growing environment for steady food and seed output',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['greenhouse', 'glasshouse'],
            strictOsmMatch: true,
            buildCost: 360,
            buildTime: 7000,
        },
        HYDROPONICS_FARM: {
            id: 'hydroponics_farm',
            name: 'Hydroponics Farm',
            description: 'Tiny self-contained urban food system with morale benefits',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['hydroponics'],
            strictOsmMatch: true,
            buildCost: 380,
            buildTime: 7200,
        },
        COMMUNITY_KITCHEN: {
            id: 'community_kitchen',
            name: 'Community Kitchen',
            description: 'Repurposed building that produces a small amount of food',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['yes'],
            buildCost: 280,
            buildTime: 5200,
        },
        SMOKEHOUSE: {
            id: 'smokehouse',
            name: 'Smokehouse',
            description: 'Warehouse-based food preservation and preparation center',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['warehouse', 'storage'],
            strictOsmMatch: true,
            buildCost: 320,
            buildTime: 6200,
        },
        CANNERY: {
            id: 'cannery',
            name: 'Cannery',
            description: 'Large-scale preservation plant for long-term food output',
            defense: 155,
            jobSlots: 3,
            osmTypes: ['industrial', 'factory'],
            strictOsmMatch: true,
            buildCost: 370,
            buildTime: 7300,
        },
        AQUAPONICS_LAB: {
            id: 'aquaponics_lab',
            name: 'Aquaponics Lab',
            description: 'Integrated fish and crop production at high efficiency',
            defense: 160,
            jobSlots: 2,
            osmTypes: ['aquaponics'],
            strictOsmMatch: true,
            buildCost: 410,
            buildTime: 7600,
        },
        SEED_DEPOT: {
            id: 'seed_depot',
            name: 'Seed Depot',
            description: 'Seed storage and propagation hub',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['silo', 'granary'],
            buildCost: 320,
            buildTime: 6200,
        },
        SEED_BANK: {
            id: 'seed_bank',
            name: 'Seed Bank',
            description: 'Managed reserve of viable seeds for long-term survival',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['storage', 'warehouse'],
            strictOsmMatch: true,
            buildCost: 335,
            buildTime: 6400,
        },
        BARN_DEPOT: {
            id: 'barn_depot',
            name: 'Barn Depot',
            description: 'Barn conversion focused on local seed handling',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['barn'],
            strictOsmMatch: true,
            buildCost: 300,
            buildTime: 6000,
        },
        URBAN_GARDEN: {
            id: 'urban_garden',
            name: 'Urban Garden',
            description: 'City allotment plots that yield modest food and seed stocks',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['allotments', 'community_garden'],
            strictOsmMatch: true,
            buildCost: 300,
            buildTime: 5800,
        },
        PROPAGATION_HOUSE: {
            id: 'propagation_house',
            name: 'Propagation House',
            description: 'Controlled propagation site focused on seed multiplication',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['greenhouse', 'glasshouse'],
            strictOsmMatch: true,
            buildCost: 340,
            buildTime: 6500,
        },
        MARKET_GARDEN: {
            id: 'market_garden',
            name: 'Market Garden',
            description: 'Small urban produce operation tied to local markets',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['marketplace', 'farmers_market'],
            strictOsmMatch: true,
            buildCost: 320,
            buildTime: 6100,
        },
        AGRONOMY_CENTER: {
            id: 'agronomy_center',
            name: 'Agronomy Center',
            description: 'Advanced seed and crop science center for optimized yield',
            defense: 155,
            jobSlots: 2,
            osmTypes: ['research', 'university', 'laboratory'],
            strictOsmMatch: true,
            buildCost: 370,
            buildTime: 7200,
        },
        NURSERY: {
            id: 'nursery',
            name: 'Plant Nursery',
            description: 'Specialized cultivation focused on high seed output',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['plant_nursery'],
            strictOsmMatch: true,
            buildCost: 315,
            buildTime: 6000,
        },
        GENETIC_SEED_VAULT: {
            id: 'genetic_seed_vault',
            name: 'Genetic Seed Vault',
            description: 'Top-tier protected repository preserving elite seed stock',
            defense: 170,
            jobSlots: 2,
            osmTypes: ['seed_bank'],
            strictOsmMatch: true,
            buildCost: 430,
            buildTime: 7800,
        },
        MILL: {
            id: 'mill',
            name: 'Mill',
            description: 'Converts large amounts of seeds into food',
            defense: 150,
            jobSlots: 4,
            osmTypes: ['mill'],
            strictOsmMatch: true,
            buildCost: 360,
            scrapCost: 50,
            toolCost: 5,
            buildTime: 7500,
        },
        // Tier 2 - Residential additions
        SMALL_APARTMENT: {
            id: 'small_apartment',
            name: 'Small Apartment Complex',
            description: 'Modest multi-unit residential building',
            defense: 115,
            bedsMin: 10,
            bedsMax: 16,
            storageCapacity: 70,
            jobSlots: 1,
            osmTypes: ['apartments', 'residential'],
            buildCost: 210,
            buildTime: 4100,
        },
        TOWNHOUSE_BLOCK: {
            id: 'townhouse_block',
            name: 'Townhouse Block',
            description: 'Clustered townhouses providing efficient housing',
            defense: 120,
            bedsMin: 11,
            bedsMax: 18,
            storageCapacity: 72,
            jobSlots: 1,
            osmTypes: ['detached', 'semi_detached'],
            buildCost: 215,
            buildTime: 4200,
        },
        // Tier 2 - Food additions
        CANNING_HUT: {
            id: 'canning_hut',
            name: 'Canning Hut',
            description: 'Small-scale food preservation facility',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['industrial', 'workshop'],
            buildCost: 310,
            buildTime: 6100,
        },
        // Tier 2 - Seeds additions
        GRAIN_SILO: {
            id: 'grain_silo',
            name: 'Grain Silo',
            description: 'Bulk seed and grain storage structure',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['silo', 'storage'],
            strictOsmMatch: true,
            buildCost: 325,
            buildTime: 6300,
        },
        DRY_STORAGE: {
            id: 'dry_storage',
            name: 'Dry Storage Building',
            description: 'Controlled-environment seed and grain storage',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['warehouse', 'storage'],
            buildCost: 330,
            buildTime: 6350,
        },
        // Tier 2 - Soldiers additions
        DRILL_YARD: {
            id: 'drill_yard',
            name: 'Drill Yard',
            description: 'Open training area for basic soldier conditioning',
            defense: 160,
            jobSlots: 3,
            osmTypes: ['barracks', 'military', 'sports_centre'],
            buildCost: 420,
            scrapCost: 105,
            buildTime: 9600,
        },
        BARRACKS_COMPOUND: {
            id: 'barracks_compound',
            name: 'Barracks Compound',
            description: 'Fortified military housing and training complex',
            defense: 170,
            jobSlots: 3,
            osmTypes: ['barracks', 'military'],
            strictOsmMatch: true,
            buildCost: 440,
            scrapCost: 115,
            buildTime: 9900,
        },
        // Tier 2 - Fortifications additions
        GARRISON_POST: {
            id: 'garrison_post',
            name: 'Garrison Post',
            description: 'Small fortified outpost for local defense',
            defense: 750,
            jobSlots: 1,
            osmTypes: ['fort', 'military', 'defensive'],
            buildCost: 480,
            scrapCost: 125,
            buildTime: 10600,
        },
        DEFENSIVE_LINE: {
            id: 'defensive_line',
            name: 'Defensive Line',
            description: 'Linear fortifications for perimeter defense',
            defense: 720,
            jobSlots: 1,
            osmTypes: ['wall', 'defensive', 'fortress'],
            buildCost: 475,
            scrapCost: 122,
            buildTime: 10500,
        },
        // Tier 3 - Residential additions
        VILLA_CLUSTER: {
            id: 'villa_cluster',
            name: 'Villa Cluster',
            description: 'Semi-detached villas with private gardens',
            defense: 128,
            bedsMin: 13,
            bedsMax: 22,
            storageCapacity: 85,
            jobSlots: 2,
            osmTypes: ['residential', 'detached'],
            buildCost: 260,
            buildTime: 5000,
        },
        // Tier 3 - Food additions
        PROCESSING_PLANT: {
            id: 'processing_plant',
            name: 'Food Processing Plant',
            description: 'Industrial-scale food processing and distribution',
            defense: 152,
            jobSlots: 4,
            osmTypes: ['industrial', 'factory'],
            strictOsmMatch: true,
            buildCost: 380,
            scrapCost: 55,
            toolCost: 5,
            buildTime: 7600,
        },
        SMOKING_FACTORY: {
            id: 'smoking_factory',
            name: 'Smoking Factory',
            description: 'Large-scale meat and fish smoking operation',
            defense: 150,
            jobSlots: 3,
            osmTypes: ['industrial', 'factory', 'warehouse'],
            buildCost: 375,
            buildTime: 7400,
        },
        // Tier 3 - Seeds additions
        HEIRLOOM_GARDEN: {
            id: 'heirloom_garden',
            name: 'Heirloom Garden',
            description: 'Specialty heritage seed cultivation',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['garden_centre', 'allotments', 'community_garden'],
            strictOsmMatch: true,
            buildCost: 345,
            buildTime: 6600,
        },
        GERMINATION_CHAMBER: {
            id: 'germination_chamber',
            name: 'Germination Chamber',
            description: 'Controlled sprouting facility for seed multiplication',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['greenhouse', 'laboratory'],
            buildCost: 350,
            buildTime: 6700,
        },
        // Tier 3 - Soldiers additions
        WEAPONS_DEPOT: {
            id: 'weapons_depot',
            name: 'Weapons Depot',
            description: 'Secure armory for weapons storage and logistics',
            defense: 190,
            jobSlots: 2,
            osmTypes: ['warehouse', 'military'],
            strictOsmMatch: true,
            buildCost: 380,
            scrapCost: 70,
            toolCost: 4,
            buildTime: 8500,
        },
        TACTICAL_CENTER: {
            id: 'tactical_center',
            name: 'Tactical Training Center',
            description: 'Advanced military tactics and strategy school',
            defense: 195,
            jobSlots: 2,
            osmTypes: ['military', 'educational'],
            buildCost: 385,
            scrapCost: 72,
            toolCost: 4,
            buildTime: 8600,
        },
        // Tier 3 - Fortifications additions
        FORTIFIED_MANOR: {
            id: 'fortified_manor',
            name: 'Fortified Manor',
            description: 'Noble estate converted into defensive stronghold',
            defense: 920,
            jobSlots: 2,
            osmTypes: ['castle', 'manor', 'fortress'],
            buildCost: 540,
            scrapCost: 170,
            buildTime: 11600,
        },
        STRONGPOINT: {
            id: 'strongpoint',
            name: 'Strongpoint',
            description: 'Elevated defensive fortification with wide sightlines',
            defense: 950,
            jobSlots: 2,
            osmTypes: ['fort', 'fortress', 'tower'],
            strictOsmMatch: true,
            buildCost: 545,
            scrapCost: 172,
            buildTime: 11700,
        },
        // Tier 4 - Residential additions
        UPSCALE_RESIDENTIAL: {
            id: 'upscale_residential',
            name: 'Upscale Residential District',
            description: 'High-quality planned residential area with amenities',
            defense: 132,
            bedsMin: 18,
            bedsMax: 28,
            storageCapacity: 105,
            jobSlots: 2,
            osmTypes: ['residential', 'apartments'],
            buildCost: 310,
            buildTime: 5800,
        },
        TOWER_RESIDENTIAL: {
            id: 'tower_residential',
            name: 'Residential Tower',
            description: 'Vertical residential district for high-density housing',
            defense: 135,
            bedsMin: 22,
            bedsMax: 32,
            storageCapacity: 115,
            jobSlots: 2,
            osmTypes: ['tower', 'apartments'],
            strictOsmMatch: true,
            buildCost: 325,
            buildTime: 6000,
        },
        // Tier 4 - Food additions
        FOOD_FACTORY: {
            id: 'food_factory',
            name: 'Food Processing Factory',
            description: 'Massive industrial food production complex',
            defense: 160,
            jobSlots: 4,
            osmTypes: ['industrial', 'factory'],
            strictOsmMatch: true,
            buildCost: 400,
            scrapCost: 80,
            toolCost: 7,
            buildTime: 8000,
        },
        PRESERVATION_LAB: {
            id: 'preservation_lab',
            name: 'Food Preservation Laboratory',
            description: 'Research-driven food preservation and extension facility',
            defense: 158,
            jobSlots: 3,
            osmTypes: ['laboratory', 'industrial'],
            buildCost: 395,
            scrapCost: 78,
            toolCost: 7,
            buildTime: 7800,
        },
        // Tier 4 - Seeds additions
        SEED_LAB: {
            id: 'seed_lab',
            name: 'Seed Research Laboratory',
            description: 'Advanced genetic and breeding research facility',
            defense: 155,
            jobSlots: 2,
            osmTypes: ['laboratory', 'research', 'university'],
            strictOsmMatch: true,
            buildCost: 375,
            scrapCost: 60,
            toolCost: 6,
            buildTime: 7300,
        },
        CULTIVATION_FACILITY: {
            id: 'cultivation_facility',
            name: 'Cultivation Facility',
            description: 'Large-scale seed production and processing complex',
            defense: 157,
            jobSlots: 3,
            osmTypes: ['greenhouse', 'industrial', 'facility'],
            buildCost: 380,
            scrapCost: 62,
            toolCost: 6,
            buildTime: 7400,
        },
        // Tier 4 - Soldiers additions
        FIELD_COMMAND: {
            id: 'field_command',
            name: 'Field Command Center',
            description: 'Mobile command and coordination for military operations',
            defense: 240,
            jobSlots: 2,
            osmTypes: ['military', 'command'],
            buildCost: 485,
            scrapCost: 140,
            toolCost: 8,
            buildTime: 10800,
        },
        SIEGE_WORKSHOP: {
            id: 'siege_workshop',
            name: 'Siege Warfare Workshop',
            description: 'Construction and maintenance for siege equipment',
            defense: 235,
            jobSlots: 2,
            osmTypes: ['workshop', 'military'],
            strictOsmMatch: true,
            buildCost: 480,
            scrapCost: 138,
            toolCost: 8,
            buildTime: 10700,
        },
        // Tier 4 - Fortifications additions
        FORTRESS_COMPLEX: {
            id: 'fortress_complex',
            name: 'Fortress Complex',
            description: 'Multi-layered fortress with integrated fortifications',
            defense: 1350,
            jobSlots: 2,
            osmTypes: ['fortress', 'castle'],
            strictOsmMatch: true,
            buildCost: 580,
            scrapCost: 190,
            toolCost: 8,
            buildTime: 12200,
        },
        TURRET_BATTERY: {
            id: 'turret_battery',
            name: 'Turret Battery',
            description: 'Elevated fortification with multiple defensive positions',
            defense: 1320,
            jobSlots: 2,
            osmTypes: ['tower', 'radar_tower', 'fortress'],
            buildCost: 570,
            scrapCost: 188,
            toolCost: 8,
            buildTime: 12100,
        },
        // Keep existing Tier 4+ buildings that need tier reassignment
        HIGH_RISE_TOWER: {
            id: 'high_rise_tower',
            name: 'High-Rise Tower',
            description: 'Vertical housing tower with large civilian capacity',
            defense: 140,
            bedsMin: 24,
            bedsMax: 36,
            storageCapacity: 140,
            jobSlots: 2,
            osmTypes: ['tower'],
            strictOsmMatch: true,
            buildCost: 360,
            buildTime: 7000,
        },
        AQUAPONICS_LAB: {
            id: 'aquaponics_lab',
            name: 'Aquaponics Laboratory',
            description: 'Integrated fish and crop production at high efficiency',
            defense: 160,
            jobSlots: 2,
            osmTypes: ['aquaponics'],
            strictOsmMatch: true,
            buildCost: 410,
            buildTime: 7600,
        },
        NURSERY: {
            id: 'nursery',
            name: 'Plant Nursery',
            description: 'Specialized cultivation focused on high seed output',
            defense: 150,
            jobSlots: 2,
            osmTypes: ['plant_nursery'],
            strictOsmMatch: true,
            buildCost: 315,
            buildTime: 6000,
        },
    },

    MAIN_BUILDING_STARTERS: ['HOUSE', 'COMMUNITY_KITCHEN', 'SEED_DEPOT', 'ARMORY', 'FORTIFICATION'],

    OSM_TAG_RESTRICTIONS: {
        farm: ['COMMUNITY_KITCHEN'],
        farmland: ['COMMUNITY_KITCHEN'],
        forest: ['COMMUNITY_KITCHEN'],
        wood: ['COMMUNITY_KITCHEN'],
        barracks: ['ARMORY'],
        military: ['ARMORY'],
        fort: ['FORTIFICATION'],
        fortress: ['FORTIFICATION'],
        castle: ['FORTIFICATION'],
        warehouse: ['COMMUNITY_KITCHEN', 'SEED_DEPOT'],
        storage: ['COMMUNITY_KITCHEN', 'SEED_DEPOT'],
        silo: ['SEED_DEPOT'],
        granary: ['SEED_DEPOT'],
        mill: ['COMMUNITY_KITCHEN'],
        garden_centre: ['SEED_DEPOT'],
        plant_nursery: ['SEED_DEPOT'],
        allotments: ['SEED_DEPOT'],
        community_garden: ['SEED_DEPOT'],
        farmers_market: ['SEED_DEPOT'],
        marketplace: ['SEED_DEPOT'],
        greenhouse: ['COMMUNITY_KITCHEN'],
        glasshouse: ['COMMUNITY_KITCHEN'],
        orchard: ['COMMUNITY_KITCHEN'],
        vineyard: ['COMMUNITY_KITCHEN'],
        aquaponics: ['COMMUNITY_KITCHEN'],
        hydroponics: ['COMMUNITY_KITCHEN'],
    },

    UPGRADE_COSTS_BY_TIER: {
        1: { scrap: 0, tools: 0 },
        2: { scrap: 40, tools: 3 },
        3: { scrap: 80, tools: 6 },
        4: { scrap: 130, tools: 9 },
        5: { scrap: 190, tools: 13 },
    },

    BUILDING_PROGRESSION: {
        tiers: {
            HQ: 1,
            HOUSE: 1,
            COMMUNITY_KITCHEN: 1,
            SEED_DEPOT: 1,
            ARMORY: 1,
            FORTIFICATION: 1,

            COTTAGE_BLOCK: 2,
            ROW_HOUSING: 2,
            SMALL_APARTMENT: 2,
            TOWNHOUSE_BLOCK: 2,
            FARM: 2,
            FIELD_KITCHEN: 2,
            SMOKEHOUSE: 2,
            CANNING_HUT: 2,
            BARN_DEPOT: 2,
            SEED_BANK: 2,
            GRAIN_SILO: 2,
            DRY_STORAGE: 2,
            TRAINING_GROUNDS: 2,
            DRILL_YARD: 2,
            BARRACKS_COMPOUND: 2,
            PALISADE: 2,
            GARRISON_POST: 2,
            DEFENSIVE_LINE: 2,

            TENEMENT: 3,
            VILLA_CLUSTER: 3,
            ORCHARD: 3,
            PROCESSING_PLANT: 3,
            SMOKING_FACTORY: 3,
            URBAN_GARDEN: 3,
            PROPAGATION_HOUSE: 3,
            HEIRLOOM_GARDEN: 3,
            GERMINATION_CHAMBER: 3,
            MILL: 3,
            GUNSMITH: 3,
            WEAPONS_DEPOT: 3,
            TACTICAL_CENTER: 3,
            CASTLE_KEEP: 3,
            FORTIFIED_MANOR: 3,
            STRONGPOINT: 3,

            HOSTEL: 4,
            RESIDENTIAL_COMPLEX: 4,
            UPSCALE_RESIDENTIAL: 4,
            TOWER_RESIDENTIAL: 4,
            GREENHOUSE: 4,
            CANNERY: 4,
            FOOD_FACTORY: 4,
            PRESERVATION_LAB: 4,
            MARKET_GARDEN: 4,
            AGRONOMY_CENTER: 4,
            SEED_LAB: 4,
            CULTIVATION_FACILITY: 4,
            MUNITIONS_FACTORY: 4,
            FIELD_COMMAND: 4,
            SIEGE_WORKSHOP: 4,
            BASTION: 4,
            FORTRESS_COMPLEX: 4,
            TURRET_BATTERY: 4,
            HIGH_RISE_TOWER: 4,
            AQUAPONICS_LAB: 4,
            NURSERY: 4,

            APARTMENT_BUILDING: 5,
            HYDROPONICS_FARM: 5,
            GENETIC_SEED_VAULT: 5,
            WAR_COLLEGE: 5,
            CITADEL: 5,
        },
        upgrades: {
            // Residential progression
            HOUSE: ['COTTAGE_BLOCK', 'ROW_HOUSING', 'SMALL_APARTMENT', 'TOWNHOUSE_BLOCK'],
            COTTAGE_BLOCK: ['TENEMENT', 'VILLA_CLUSTER'],
            ROW_HOUSING: ['TENEMENT', 'VILLA_CLUSTER'],
            SMALL_APARTMENT: ['TENEMENT', 'VILLA_CLUSTER'],
            TOWNHOUSE_BLOCK: ['TENEMENT', 'VILLA_CLUSTER'],
            TENEMENT: ['HOSTEL', 'RESIDENTIAL_COMPLEX', 'UPSCALE_RESIDENTIAL'],
            VILLA_CLUSTER: ['HOSTEL', 'RESIDENTIAL_COMPLEX', 'UPSCALE_RESIDENTIAL'],
            HOSTEL: ['APARTMENT_BUILDING', 'TOWER_RESIDENTIAL'],
            RESIDENTIAL_COMPLEX: ['APARTMENT_BUILDING', 'TOWER_RESIDENTIAL'],
            UPSCALE_RESIDENTIAL: ['APARTMENT_BUILDING', 'TOWER_RESIDENTIAL'],
            TOWER_RESIDENTIAL: ['APARTMENT_BUILDING'],
            HIGH_RISE_TOWER: ['APARTMENT_BUILDING'],

            // Food progression
            COMMUNITY_KITCHEN: ['FARM', 'SMOKEHOUSE', 'FIELD_KITCHEN', 'CANNING_HUT'],
            FARM: ['ORCHARD'],
            SMOKEHOUSE: ['PROCESSING_PLANT', 'SMOKING_FACTORY'],
            FIELD_KITCHEN: ['ORCHARD'],
            CANNING_HUT: ['PROCESSING_PLANT', 'SMOKING_FACTORY'],
            ORCHARD: ['GREENHOUSE', 'CANNERY', 'FOOD_FACTORY'],
            PROCESSING_PLANT: ['GREENHOUSE', 'CANNERY', 'FOOD_FACTORY'],
            SMOKING_FACTORY: ['GREENHOUSE', 'CANNERY', 'FOOD_FACTORY'],
            MILL: ['GREENHOUSE', 'CANNERY', 'FOOD_FACTORY'],
            GREENHOUSE: ['HYDROPONICS_FARM', 'PRESERVATION_LAB'],
            CANNERY: ['HYDROPONICS_FARM', 'AQUAPONICS_LAB', 'PRESERVATION_LAB'],
            FOOD_FACTORY: ['HYDROPONICS_FARM', 'AQUAPONICS_LAB'],
            PRESERVATION_LAB: ['HYDROPONICS_FARM'],
            AQUAPONICS_LAB: ['HYDROPONICS_FARM'],

            // Seeds progression
            SEED_DEPOT: ['BARN_DEPOT', 'SEED_BANK', 'GRAIN_SILO', 'DRY_STORAGE'],
            BARN_DEPOT: ['URBAN_GARDEN', 'HEIRLOOM_GARDEN'],
            SEED_BANK: ['PROPAGATION_HOUSE'],
            GRAIN_SILO: ['URBAN_GARDEN', 'HEIRLOOM_GARDEN'],
            DRY_STORAGE: ['PROPAGATION_HOUSE'],
            URBAN_GARDEN: ['MARKET_GARDEN'],
            PROPAGATION_HOUSE: ['GERMINATION_CHAMBER', 'AGRONOMY_CENTER'],
            HEIRLOOM_GARDEN: ['MARKET_GARDEN'],
            GERMINATION_CHAMBER: ['AGRONOMY_CENTER'],
            MARKET_GARDEN: ['SEED_LAB', 'CULTIVATION_FACILITY'],
            AGRONOMY_CENTER: ['SEED_LAB', 'CULTIVATION_FACILITY', 'NURSERY'],
            SEED_LAB: ['GENETIC_SEED_VAULT'],
            CULTIVATION_FACILITY: ['GENETIC_SEED_VAULT'],
            NURSERY: ['GENETIC_SEED_VAULT'],

            // Soldiers progression
            ARMORY: ['TRAINING_GROUNDS', 'DRILL_YARD', 'BARRACKS_COMPOUND'],
            TRAINING_GROUNDS: ['GUNSMITH'],
            DRILL_YARD: ['GUNSMITH', 'WEAPONS_DEPOT'],
            BARRACKS_COMPOUND: ['GUNSMITH', 'WEAPONS_DEPOT'],
            GUNSMITH: ['TACTICAL_CENTER', 'MUNITIONS_FACTORY'],
            WEAPONS_DEPOT: ['TACTICAL_CENTER', 'MUNITIONS_FACTORY'],
            TACTICAL_CENTER: ['FIELD_COMMAND', 'SIEGE_WORKSHOP', 'MUNITIONS_FACTORY'],
            MUNITIONS_FACTORY: ['FIELD_COMMAND', 'SIEGE_WORKSHOP', 'WAR_COLLEGE'],
            FIELD_COMMAND: ['WAR_COLLEGE'],
            SIEGE_WORKSHOP: ['WAR_COLLEGE'],

            // Fortifications progression
            FORTIFICATION: ['PALISADE', 'GARRISON_POST', 'DEFENSIVE_LINE'],
            PALISADE: ['CASTLE_KEEP'],
            GARRISON_POST: ['CASTLE_KEEP', 'FORTIFIED_MANOR'],
            DEFENSIVE_LINE: ['CASTLE_KEEP', 'FORTIFIED_MANOR'],
            CASTLE_KEEP: ['STRONGPOINT', 'BASTION', 'FORTRESS_COMPLEX'],
            FORTIFIED_MANOR: ['STRONGPOINT', 'BASTION', 'FORTRESS_COMPLEX'],
            STRONGPOINT: ['BASTION', 'TURRET_BATTERY', 'CITADEL'],
            BASTION: ['TURRET_BATTERY', 'CITADEL'],
            FORTRESS_COMPLEX: ['TURRET_BATTERY', 'CITADEL'],
            TURRET_BATTERY: ['CITADEL'],
        },
    },
    
    // Job definitions
    JOBS: {
        FARMING: {
            id: 'farming',
            name: 'Farmer',
            building: 'farm',
            foodConsumption: 1, // food per second per citizen
            seedConsumption: 0.1, // seeds per second (small amount to sustain crops)
            foodProduction: 2, // food per second
            xpRate: 0.5,
        },
        GATHERING: {
            id: 'gathering',
            name: 'Gatherer',
            building: 'gathering_station',
            foodConsumption: 0.8,
            foodProduction: 1, // food per second
            seedProduction: 0.5, // seeds per second (increased from 0.3)
            xpRate: 0.4,
        },
        SCAVENGING: {
            id: 'scavenging',
            name: 'Scavenger',
            building: null, // No building required
            foodConsumption: 0.5,
            scrapProduction: 0.2, // scrap per second
            xpRate: 0.3,
        },
        MILITARY: {
            id: 'military',
            name: 'Soldier',
            building: 'armory',
            foodConsumption: 1.2,
            scrapConsumption: 0.1, // scrap for equipment maintenance
            xpRate: 0.6,
        },
        GUNSMITH: {
            id: 'gunsmith',
            name: 'Gunsmith',
            building: 'gunsmith',
            description: 'Improves soldier weapon quality and reliability',
            foodConsumption: 0.7,
            scrapConsumption: 0.25,
            xpRate: 0.5,
        },
        ENTERTAINMENT: {
            id: 'entertainment',
            name: 'Entertainer',
            building: 'entertainment',
            foodConsumption: 0.6,
            happinessProduction: 3.8,
            xpRate: 0.4,
        },
        NIGHT_HOST: {
            id: 'night_host',
            name: 'Night Host',
            building: 'nightclub',
            foodConsumption: 0.65,
            happinessProduction: 4.1,
            xpRate: 0.41,
        },
        BREWER: {
            id: 'brewer',
            name: 'Brewer',
            building: 'brewery',
            foodConsumption: 0.5,
            seedConsumption: 0.8, // seeds per second (main resource)
            happinessProduction: 3.1,
            xpRate: 0.4,
        },
        PRIEST: {
            id: 'priest',
            name: 'Clergy',
            building: 'religious',
            foodConsumption: 0.4,
            religiousnessProduction: 0.9,
            xpRate: 0.3,
        },
        ENGINEER: {
            id: 'engineer',
            name: 'Engineer',
            building: 'workshop',
            foodConsumption: 0.7,
            scrapConsumption: 0.35,
            toolsProduction: 0.4,
            xpRate: 0.45,
        },
        HEALER: {
            id: 'healer',
            name: 'Healer',
            building: 'clinic',
            foodConsumption: 0.6,
            happinessProduction: 2.6,
            xpRate: 0.35,
        },
        IRRIGATOR: {
            id: 'irrigator',
            name: 'Irrigation Worker',
            building: 'waterworks',
            foodConsumption: 0.6,
            seedProduction: 0.35,
            farmEfficiencyBonus: 0.08,
            xpRate: 0.4,
        },
        PUMP_OPERATOR: {
            id: 'pump_operator',
            name: 'Pump Operator',
            building: 'pumping_station',
            foodConsumption: 0.58,
            seedProduction: 0.3,
            farmEfficiencyBonus: 0.05,
            xpRate: 0.39,
        },
        ORCHARDER: {
            id: 'orcharder',
            name: 'Orchard Worker',
            building: 'orchard',
            foodConsumption: 0.7,
            seedConsumption: 0.12,
            foodProduction: 1.9,
            seedProduction: 0.2,
            xpRate: 0.42,
        },
        HORTICULTURIST: {
            id: 'horticulturist',
            name: 'Horticulturist',
            building: 'greenhouse',
            foodConsumption: 0.6,
            seedConsumption: 0.2,
            foodProduction: 1.4,
            seedProduction: 0.55,
            xpRate: 0.43,
        },
        HYDROPONICS_TECH: {
            id: 'hydroponics_tech',
            name: 'Hydroponics Tech',
            building: 'hydroponics_farm',
            foodConsumption: 0.45,
            foodProduction: 0.45,
            happinessProduction: 0.6,
            xpRate: 0.36,
        },
        KITCHEN_STAFF: {
            id: 'kitchen_staff',
            name: 'Kitchen Staff',
            building: 'community_kitchen',
            foodConsumption: 0.45,
            foodProduction: 0.75,
            xpRate: 0.34,
        },
        FIELD_COOK: {
            id: 'field_cook',
            name: 'Field Cook',
            building: 'field_kitchen',
            foodConsumption: 0.5,
            seedConsumption: 0.1,
            foodProduction: 1.0,
            xpRate: 0.35,
        },
        SMOKEHOUSE_WORKER: {
            id: 'smokehouse_worker',
            name: 'Smokehouse Worker',
            building: 'smokehouse',
            foodConsumption: 0.55,
            seedConsumption: 0.2,
            foodProduction: 1.9,
            xpRate: 0.38,
        },
        CANNER: {
            id: 'canner',
            name: 'Canner',
            building: 'cannery',
            foodConsumption: 0.58,
            seedConsumption: 0.24,
            foodProduction: 2.2,
            xpRate: 0.41,
        },
        AQUAPONICS_ENGINEER: {
            id: 'aquaponics_engineer',
            name: 'Aquaponics Engineer',
            building: 'aquaponics_lab',
            foodConsumption: 0.52,
            seedConsumption: 0.16,
            foodProduction: 2.6,
            seedProduction: 0.35,
            xpRate: 0.44,
        },
        INNKEEPER: {
            id: 'innkeeper',
            name: 'Innkeeper',
            building: 'hostel',
            foodConsumption: 0.55,
            happinessProduction: 1.8,
            xpRate: 0.35,
        },
        COTTAGE_KEEPER: {
            id: 'cottage_keeper',
            name: 'Cottage Keeper',
            building: 'cottage_block',
            foodConsumption: 0.5,
            seedProduction: 0.15,
            xpRate: 0.33,
        },
        SEEDKEEPER: {
            id: 'seedkeeper',
            name: 'Seedkeeper',
            building: 'seed_depot',
            foodConsumption: 0.5,
            seedProduction: 0.95,
            xpRate: 0.4,
        },
        BARN_KEEPER: {
            id: 'barn_keeper',
            name: 'Barn Keeper',
            building: 'barn_depot',
            foodConsumption: 0.48,
            seedProduction: 0.7,
            xpRate: 0.37,
        },
        SEED_CURATOR: {
            id: 'seed_curator',
            name: 'Seed Curator',
            building: 'seed_bank',
            foodConsumption: 0.5,
            seedProduction: 0.78,
            xpRate: 0.39,
        },
        URBAN_FARMER: {
            id: 'urban_farmer',
            name: 'Urban Farmer',
            building: 'urban_garden',
            foodConsumption: 0.6,
            seedConsumption: 0.08,
            foodProduction: 1.2,
            seedProduction: 0.25,
            xpRate: 0.38,
        },
        PROPAGATOR: {
            id: 'propagator',
            name: 'Propagator',
            building: 'propagation_house',
            foodConsumption: 0.52,
            seedProduction: 0.82,
            xpRate: 0.4,
        },
        MARKET_GROWER: {
            id: 'market_grower',
            name: 'Market Grower',
            building: 'market_garden',
            foodConsumption: 0.6,
            seedConsumption: 0.1,
            foodProduction: 1.35,
            seedProduction: 0.2,
            xpRate: 0.39,
        },
        AGRONOMIST: {
            id: 'agronomist',
            name: 'Agronomist',
            building: 'agronomy_center',
            foodConsumption: 0.55,
            seedProduction: 0.92,
            xpRate: 0.43,
        },
        NURSERY_KEEPER: {
            id: 'nursery_keeper',
            name: 'Nursery Keeper',
            building: 'nursery',
            foodConsumption: 0.5,
            seedProduction: 0.85,
            xpRate: 0.38,
        },
        VAULT_KEEPER: {
            id: 'vault_keeper',
            name: 'Vault Keeper',
            building: 'genetic_seed_vault',
            foodConsumption: 0.56,
            seedProduction: 1.15,
            xpRate: 0.46,
        },
        MILLING: {
            id: 'milling',
            name: 'Miller',
            building: 'mill',
            foodConsumption: 0.8,
            seedConsumption: 1.4,
            foodProduction: 4.2,
            xpRate: 0.45,
        },
        CASTLE_WARDEN: {
            id: 'castle_warden',
            name: 'Castle Warden',
            building: 'castle_keep',
            foodConsumption: 0.95,
            scrapConsumption: 0.08,
            xpRate: 0.5,
        },
        DRILL_INSTRUCTOR: {
            id: 'drill_instructor',
            name: 'Drill Instructor',
            building: 'training_grounds',
            foodConsumption: 0.9,
            scrapConsumption: 0.06,
            xpRate: 0.48,
        },
        ORDNANCE_TECH: {
            id: 'ordnance_tech',
            name: 'Ordnance Technician',
            building: 'munitions_factory',
            foodConsumption: 0.92,
            scrapConsumption: 0.2,
            toolsProduction: 0.15,
            xpRate: 0.52,
        },
        STRATEGIST: {
            id: 'strategist',
            name: 'Strategist',
            building: 'war_college',
            foodConsumption: 0.88,
            xpRate: 0.55,
        },
        SENTRY: {
            id: 'sentry',
            name: 'Sentry',
            building: 'palisade',
            foodConsumption: 0.8,
            xpRate: 0.44,
        },
        BASTION_ENGINEER: {
            id: 'bastion_engineer',
            name: 'Bastion Engineer',
            building: 'bastion',
            foodConsumption: 0.86,
            scrapConsumption: 0.12,
            xpRate: 0.5,
        },
        CITADEL_COMMANDER: {
            id: 'citadel_commander',
            name: 'Citadel Commander',
            building: 'citadel',
            foodConsumption: 0.9,
            xpRate: 0.58,
        },
    },
    
    // Resource costs and requirements
    RESOURCES: {
        foodPerCitizen: 1, // food consumed per citizen per second
        storagePerFood: 1, // storage space per food unit
        storagePerSeed: 0.5,
        storagePerScrap: 0.3,
        storagePerTools: 0.4,
        storagePerSoldier: 0.6,
        bedsPerCitizen: 1, // beds needed per citizen
        birthRate: 0.01, // new citizens per existing citizen per second (very slow)
    },

    COMBAT: {
        baseSoldierDamage: 100,
        gunsmithBonusPerWorker: 0.12,
        maxGunsmithBonus: 0.96,
    },
    
    // Time system
    TIME: {
        secondsPerDay: 300, // 5 minutes real time = 1 game day
        daysPerWeek: 7,
        survivalDays: 7, // Citizens survive 1 week without food
    },
    
    // Happiness system
    HAPPINESS: {
        baseHappiness: 72,
        maxHappiness: 100,
        minHappiness: 0,
        starvingPenalty: -15,
        wellFedBonus: 22,
        housingPenalty: -8,
        arrivalThreshold: 35, // Reduced from 40 for easier recruitment
        arrivalCheckInterval: 10, // Check for arrivals every 10 seconds (was 60)
        arrivalChance: 0.5, // 50% chance per check when happy (was 30%)
        
        // Control-based happiness modifiers
        controlModifiers: {
            high: -10,
            medium: 0,
            low: 8,
            free: 24,
        },
        religionModifiers: {
            strict: -8,
            moderate: 4,
            tolerant: 10,
            none: 16,
        },
    },

    // Crime system
    CRIME: {
        checkInterval: 20, // seconds between crime checks
        baseChanceUnder50: 0.16,
        baseChanceOver50: 0.24,
        penaltyDecayPerSecond: 0.12,
        religionLevelMultiplier: {
            strict: 0.75,
            moderate: 1.0,
            tolerant: 1.1,
            none: 1.3,
        },
        controlImpactMultiplier: {
            high: 0.6,   // least happiness impact
            medium: 1.0, // same as free
            low: 1.5,    // highest happiness impact
            free: 1.0,
        },
        under50Types: [
            {
                key: 'theft',
                label: 'Theft',
                happinessPenalty: 4,
                citizenLossChance: 0.08,
            },
            {
                key: 'murder',
                label: 'Murder',
                happinessPenalty: 8,
                citizenLossChance: 0.35,
            },
        ],
        over50Types: [
            {
                key: 'theft',
                label: 'Theft',
                happinessPenalty: 4,
                citizenLossChance: 0.08,
            },
            {
                key: 'murder',
                label: 'Murder',
                happinessPenalty: 8,
                citizenLossChance: 0.35,
            },
            {
                key: 'fraud',
                label: 'Fraud',
                happinessPenalty: 5,
                citizenLossChance: 0.05,
            },
            {
                key: 'arson',
                label: 'Arson',
                happinessPenalty: 6,
                citizenLossChance: 0.12,
            },
            {
                key: 'assault',
                label: 'Assault',
                happinessPenalty: 6,
                citizenLossChance: 0.15,
            },
            {
                key: 'kidnapping',
                label: 'Kidnapping',
                happinessPenalty: 9,
                citizenLossChance: 0.3,
            },
            {
                key: 'organizedCrime',
                label: 'Organized Crime',
                happinessPenalty: 10,
                citizenLossChance: 0.22,
            },
            {
                key: 'riot',
                label: 'Riot',
                happinessPenalty: 11,
                citizenLossChance: 0.25,
            },
        ],
    },
    
    // Government system
    GOVERNMENT: {
        controlLevels: {
            high: {
                name: 'High Control',
                description: 'Direct job assignment, citizens cannot quit or leave',
                happinessMod: -20,
                playerControlsJobs: true,
                citizensCanQuit: false,
                citizensCanLeave: false,
                aiJobChange: false,
            },
            medium: {
                name: 'Medium Control',
                description: 'Assign jobs, but citizens may occasionally change roles',
                happinessMod: -5,
                playerControlsJobs: true,
                citizensCanQuit: true,
                citizensCanLeave: false,
                aiJobChange: false,
                jobChangeChance: 0.05, // 5% per check
            },
            low: {
                name: 'Low Control',
                description: 'Citizens often change jobs on their own',
                happinessMod: 5,
                playerControlsJobs: true,
                citizensCanQuit: true,
                citizensCanLeave: false,
                aiJobChange: true,
                jobChangeChance: 0.25, // 25% per check (was 15%)
            },
            free: {
                name: 'Free Control',
                description: 'Citizens fully autonomous, may claim buildings themselves',
                happinessMod: 15,
                playerControlsJobs: false,
                citizensCanQuit: true,
                citizensCanLeave: true,
                aiJobChange: true,
                jobChangeChance: 0.3, // 30% per check when working (was 20%)
                aiClaimBuilding: true,
                claimChance: 0.15, // 15% per check when needed (was 2%)
            },
        },
        stateReligionPenaltyPerCitizen: 0.35,
        religionLevels: {
            strict: {
                name: 'Strict Religious Control',
                description: 'State religion enforced, low tolerance',
                happinessMod: -15,
            },
            moderate: {
                name: 'Moderate Religious Policy',
                description: 'Official religion with some tolerance',
                happinessMod: 0,
            },
            tolerant: {
                name: 'Religious Tolerance',
                description: 'All religions accepted equally',
                happinessMod: 5,
            },
            none: {
                name: 'Secular State',
                description: 'No official religion, complete separation',
                happinessMod: 0,
            },
        },
        defaultControl: 'medium',
        defaultReligion: 'moderate',
    },
    
    // Demographics
    DEMOGRAPHICS: {
        ageGroups: {
            child: { min: 0, max: 17, weight: 0.2, canWork: false },
            adult: { min: 18, max: 64, weight: 0.65, canWork: true },
            elder: { min: 65, max: 90, weight: 0.15, canWork: false },
        },
        genders: ['Male', 'Female'],
        religions: [
            'Christianity', 'Islam', 'Buddhism', 'Hinduism', 'Judaism',
            'Sikhism', 'Atheist', 'Agnostic', 'Other'
        ],
        ethnicities: [
            'Asian', 'Black', 'Hispanic', 'Middle Eastern',
            'Native', 'Pacific Islander', 'White', 'Mixed'
        ],
    },

    RELIGION_BUILDINGS: {
        Christianity: 'Church',
        Islam: 'Mosque',
        Buddhism: 'Temple',
        Hinduism: 'Mandir',
        Judaism: 'Synagogue',
        Sikhism: 'Gurdwara',
        Atheist: 'Humanist Center',
        Agnostic: 'Philosophy Hall',
        Other: 'Shrine',
    },

    RELIGION_JOB_TITLES: {
        Christianity: 'Priest',
        Islam: 'Imam',
        Buddhism: 'Monk',
        Hinduism: 'Pandit',
        Judaism: 'Rabbi',
        Sikhism: 'Granthi',
        Atheist: 'Humanist',
        Agnostic: 'Seeker',
        Other: 'Clergy',
    },
    
    // Known famous houses and landmarks
    KNOWN_HOUSES: [
        {
            name: 'Graceland',
            location: [-90.008, 35.048], // Memphis, Tennessee
            beds: 23,
            description: 'Elvis Presley\'s mansion',
        },
        {
            name: 'White House',
            location: [-77.0369, 38.8951], // Washington, DC
            beds: 132,
            description: 'Official residence of the US President',
        },
        {
            name: 'Biltmore Estate',
            location: [-82.555, 35.543], // Asheville, North Carolina
            beds: 250,
            description: 'George Washington Vanderbilt II\'s mansion',
        },
        {
            name: 'Hearst Castle',
            location: [-121.167, 35.695], // San Simeon, California
            beds: 165,
            description: 'William Randolph Hearst\'s castle',
        },
        {
            name: 'Monticello',
            location: [-78.464, 38.010], // Charlottesville, Virginia
            beds: 43,
            description: 'Thomas Jefferson\'s plantation home',
        },
        {
            name: "Palace of Versailles",
            location: [2.122, 48.803], // Versailles, France
            beds: 226,
            description: 'Royal residence of Louis XIV',
        },
        {
            name: 'Buckingham Palace',
            location: [51.501, -0.141], // London, UK
            beds: 775,
            description: 'Official residence of the British monarch',
        },
        {
            name: 'Istana Nurul Iman',
            location: [114.921, 4.871], // Bandar Seri Begawan, Brunei
            beds: 1788,
            description: 'Official residence of the Sultan of Brunei',
        }
    ],
    
    // AI Civilizations presets
    AI_CIVILIZATIONS: [
        { name: 'The Eastern Empire', color: '#3b82f6' },
        { name: 'Western Coalition', color: '#ef4444' },
        { name: 'Northern Alliance', color: '#8b5cf6' },
        { name: 'Southern Confederation', color: '#f59e0b' },
        { name: 'Central Republic', color: '#14b8a6' },
    ],
};

// Merge onto window for easy access
window.CONFIG = CONFIG;
